version: '3'

services:
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_test
    image: postgres:14
    ports:
      - 5433:5432
    restart: "no"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
